apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  serviceAccountName: jenkins
  containers:
    - name: helm
      image: lachlanevenson/k8s-helm:v3.1.1
      resources:  # limits the resources your build contaienr
        requests:
          memory: "128Mi"
          cpu: "050m"
        limits:
          memory: "512Mi"
          cpu: "100m" 
      command:
        - cat
      tty: true
